// samples/use-vue-aw/src/App.vue
<template>
  <div class="container">
    <h1>Vue</h1>
    <aw-button 
      id="primary" 
      @click="sayHello"
      @awclicked="sayHelloCustom"
      variant="primary" 
      blocked
    >
      Botão
    </aw-button>
    <p>This button was clicked {{numClicks}} times</p>

    <aw-button 
      id="secondary" 
      @click="sayHello" 
      @awclicked="sayHelloCustom"
      variant="warning" 
      blocked 
      disabled
    >
      Botão
    </aw-button>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  export default defineComponent({
    name: 'App',
    data() {
      return {
        numClicks: 0
      }
    },
    methods: {
      sayHello: function() {
        console.log('Hello Vue - sayHelloNativeEvent')
      },
      sayHelloCustom: function() {
        console.log('Hello Vue - sayHelloCustomEvent')
        this.numClicks = this.numClicks + 1
      }
    }
  });
</script>

<style>
  * {
    font-family: sans-serif;
  }
  .container {
    max-width: 300px;
    margin: 0 auto;
    padding: 1rem;
    display: flex;
    flex-direction: column;
  }
</style>

// samples/use-react-aw/src/App.tsx
import React from 'react'
import { AwButton } from 'react-aw'

import './App.css'

function App() {

  const [numClicks, setNumClicks] = React.useState(0)

  const sayHello = () => {
    console.log('Hello React - sayHelloNativeEvent')
  }

  const sayHelloCustomEvent = () => {
    console.log('Hello React - sayHelloCustomEvent')
    setNumClicks(state => state + 1)
  }

  return (
    <div className="container">
        <h1>React</h1>
        <h2>With Wrapper Lib React</h2>

        <AwButton
          variant='primary'
          blocked
          onClick={sayHello}
          onAwClicked={sayHelloCustomEvent}
        >
          Botão
        </AwButton>
        <p>This button was clicked {numClicks} times</p>

        <AwButton
          variant='warning'
          blocked
          disabled
          onClick={sayHello}
          onAwClicked={sayHelloCustomEvent}
        >
          Botão
        </AwButton>
      </div>
  );
}

export default App;
