// samples/use-react-aw-direct/src/App.tsx
import React from 'react'
import './App.css';

function App() {

  const [numClicks, setNumClicks] = React.useState(0)
  const primaryRef = React.useRef<HTMLElement | null>()

  const sayHello = () => {
    console.log('Hello React Direct - sayHelloNativeEvent')
  }

  const sayHelloCustomEvent = () => {
    console.log('Hello React Direct - sayHelloCustomEvent')
    setNumClicks(state => state + 1)
  }

  React.useEffect(() => {
    primaryRef.current?.addEventListener('awClicked', sayHelloCustomEvent)

    return () => {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      primaryRef.current?.removeEventListener('awClicked', sayHelloCustomEvent)
    }
  }, [])

  return (
    <div className="container">
      <h1>React</h1>
      <h2>Without Wrapper Lib React</h2>

      <aw-button
        ref={primaryRef}
        variant='primary'
        blocked
        onClick={sayHello}
      >
        Botão
      </aw-button>
      <p>This button was clicked {numClicks} times</p>

      <aw-button
        variant='warning'
        blocked
        disabled
        onClick={sayHello}
      >
        Botão
      </aw-button>
    </div>
  );
}

export default App;

// samples/use-vue-aw/src/App.vue
<template>
  <div class="container">
    <h1>Vue</h1>
    <aw-button 
      id="primary" 
      @click="sayHello"
      @awclicked="sayHelloCustom"
      variant="primary" 
      blocked
    >
      Botão
    </aw-button>
    <p>This button was clicked {{numClicks}} times</p>

    <aw-button 
      id="secondary" 
      @click="sayHello" 
      @awclicked="sayHelloCustom"
      variant="warning" 
      blocked 
      disabled
    >
      Botão
    </aw-button>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  export default defineComponent({
    name: 'App',
    data() {
      return {
        numClicks: 0
      }
    },
    methods: {
      sayHello: function() {
        console.log('Hello Vue - sayHelloNativeEvent')
      },
      sayHelloCustom: function() {
        console.log('Hello Vue - sayHelloCustomEvent')
        this.numClicks = this.numClicks + 1
      }
    }
  });
</script>

<style>
  * {
    font-family: sans-serif;
  }
  .container {
    max-width: 300px;
    margin: 0 auto;
    padding: 1rem;
    display: flex;
    flex-direction: column;
  }
</style>
